Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [1]:
!pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from kagglehub[pandas-datasets]) (2.2.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub[pandas-datasets]) (5.29.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->kagglehub[pandas-datasets]) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [2]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [3]:
file_path ="IMDB Dataset.csv"

In [154]:
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipykernel_2114/997064382.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.

In [155]:
df.head(5)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [156]:
data = df.copy()

In [157]:
df=data.copy()

In [158]:
def lower_text(text):
  return text.lower()

In [159]:
df.review = df.review.apply(lower_text)

In [160]:
df.head(5)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [161]:
from textblob import TextBlob

In [162]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)

In [163]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [164]:
import re

df.review = df.review.apply(lambda x: re.sub(r'<.*?>', '', x))

In [165]:
df.head(5)

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [166]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [167]:
def remove_stopwords(text):
  for words in stopwords.words('english'):
    if words in text:
      text = text.replace(words,"")
  return text

df.review = df.review.apply(remove_stopwords)

In [168]:
df.head(5)

                                              review sentiment
0  ne f  r r h enne h fer wchng  1 z epe u'  hke....  positive
1   wnerful lle prucn.  flng echnque  r unung- r ...  positive
2   hugh  w  wnerful w  pen e n   h uer eken, ng ...  positive
3  bc '  fl w  lle b (jke) hnk '  zbe n  cle &  p...  negative
4  peer e' "l n  e f ne"   vu unnng fl  wch. r. e...  positive

In [169]:
df =data.copy()

In [170]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return " ".join(filtered_words)

df["review"] = df["review"].apply(remove_stopwords)

In [171]:
df.head(5)

                                              review sentiment
0  One reviewers mentioned watching 1 Oz episode ...  positive
1  wonderful little production. <br /><br />The f...  positive
2  thought wonderful way spend time hot summer we...  positive
3  Basically there's family little boy (Jake) thi...  negative
4  Petter Mattei's "Love Time Money" visually stu...  positive

In [172]:
from nltk.stem import  PorterStemmer
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [173]:
data = df.copy()

In [174]:
lm = PorterStemmer()

In [175]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [176]:
def remove_puntuation(text):
  for punc in string.punctuation:
    if punc in text:
      text = text.replace(punc,"")
  return text

df.review = df.review.apply(remove_puntuation)

In [177]:
df.head(5)

                                              review sentiment
0  One reviewers mentioned watching 1 Oz episode ...  positive
1  wonderful little production br br The filming ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  Basically theres family little boy Jake thinks...  negative
4  Petter Matteis Love Time Money visually stunni...  positive

In [178]:
data = df.copy()

In [179]:
df=data.copy()

In [180]:
df.review = df.review.apply(lambda x: x.lower())

In [181]:
df.head(5)

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production br br the filming ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [182]:
def spelling_checker(text):
  words =  TextBlob(text).correct()

  return words

text = "hi i am your babs"
print(spelling_checker(text))

hi i am your baby

In [183]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

def stem_text(text):
    words = text.split()
    stemmed_words = [ps.stem(word) for word in words]
    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stem_text)

In [184]:
df.head(5)

                                              review sentiment
0  one review mention watch 1 oz episod hook righ...  positive
1  wonder littl product br br the film techniqu u...  positive
2  thought wonder way spend time hot summer weeke...  positive
3  basic there famili littl boy jake think there ...  negative
4  petter mattei love time money visual stun film...  positive

In [185]:
from nltk.tokenize import word_tokenize

In [186]:
vocab=dict()
vocab.update({"UNK":0})

In [187]:
vocab

{'UNK': 0}

In [188]:
def vocab_collection(text):
  words= text.split()
  for word in words:
    if word not in vocab.keys():
      vocab.update({word:len(vocab)})

In [189]:
data = df.copy()

In [190]:
df.review.apply(vocab_collection)

0        None
1        None
2        None
3        None
4        None
         ...
49995    None
49996    None
49997    None
49998    None
49999    None
Name: review, Length: 50000, dtype: object

In [191]:
vocab

{'UNK': 0,
 'one': 1,
 'review': 2,
 'mention': 3,
 'watch': 4,
 '1': 5,
 'oz': 6,
 'episod': 7,
 'hook': 8,
 'right': 9,
 'exactli': 10,
 'happen': 11,
 'mebr': 12,
 'br': 13,
 'the': 14,
 'first': 15,
 'thing': 16,
 'struck': 17,
 'brutal': 18,
 'unflinch': 19,
 'scene': 20,
 'violenc': 21,
 'set': 22,
 'word': 23,
 'go': 24,
 'trust': 25,
 'me': 26,
 'show': 27,
 'faint': 28,
 'heart': 29,
 'timid': 30,
 'pull': 31,
 'punch': 32,
 'regard': 33,
 'drug': 34,
 'sex': 35,
 'hardcor': 36,
 'classic': 37,
 'use': 38,
 'wordbr': 39,
 'it': 40,
 'call': 41,
 'nicknam': 42,
 'given': 43,
 'oswald': 44,
 'maximum': 45,
 'secur': 46,
 'state': 47,
 'penitentari': 48,
 'focus': 49,
 'mainli': 50,
 'emerald': 51,
 'citi': 52,
 'experiment': 53,
 'section': 54,
 'prison': 55,
 'cell': 56,
 'glass': 57,
 'front': 58,
 'face': 59,
 'inward': 60,
 'privaci': 61,
 'high': 62,
 'agenda': 63,
 'em': 64,
 'home': 65,
 'manyaryan': 66,
 'muslim': 67,
 'gangsta': 68,
 'latino': 69,
 'christian': 70,
 'italian': 71,
 'irish': 72,
 'moreso': 73,
 'scuffl': 74,
 'death': 75,
 'stare': 76,
 'dodgi': 77,
 'deal': 78,
 'shadi': 79,
 'agreement': 80,
 'never': 81,
 'far': 82,
 'awaybr': 83,
 'i': 84,
 'would': 85,
 'say': 86,
 'main': 87,
 'appeal': 88,
 'due': 89,
 'fact': 90,
 'goe': 91,
 'dare': 92,
 'forget': 93,
 'pretti': 94,
 'pictur': 95,
 'paint': 96,
 'mainstream': 97,
 'audienc': 98,
 'charm': 99,
 'romanceoz': 100,
 'mess': 101,
 'around': 102,
 'ever': 103,
 'saw': 104,
 'nasti': 105,
 'surreal': 106,
 'readi': 107,
 'more': 108,
 'develop': 109,
 'tast': 110,
 'got': 111,
 'accustom': 112,
 'level': 113,
 'graphic': 114,
 'injustic': 115,
 'crook': 116,
 'guard': 117,
 'wholl': 118,
 'sold': 119,
 'nickel': 120,
 'inmat': 121,
 'kill': 122,
 'order': 123,
 'get': 124,
 'away': 125,
 'well': 126,
 'manner': 127,
 'middl': 128,
 'class': 129,
 'turn': 130,
 'bitch': 131,
 'lack': 132,
 'street': 133,
 'skill': 134,
 'experi': 135,
 'may': 136,
 'becom': 137,
 'comfort': 138,
 'uncomfort': 139,
 'viewingthat': 140,
 'touch': 141,
 'darker': 142,
 'side': 143,
 'wonder': 144,
 'littl': 145,
 'product': 146,
 'film': 147,
 'techniqu': 148,
 'unassum': 149,
 'oldtimebbc': 150,
 'fashion': 151,
 'give': 152,
 'sometim': 153,
 'discomfort': 154,
 'sens': 155,
 'realism': 156,
 'entir': 157,
 'piec': 158,
 'actor': 159,
 'extrem': 160,
 'chosen': 161,
 'michael': 162,
 'sheen': 163,
 'ha': 164,
 'polari': 165,
 'voic': 166,
 'pat': 167,
 'too': 168,
 'truli': 169,
 'see': 170,
 'seamless': 171,
 'edit': 172,
 'guid': 173,
 'refer': 174,
 'william': 175,
 'diari': 176,
 'entri': 177,
 'worth': 178,
 'terrificli': 179,
 'written': 180,
 'perform': 181,
 'master': 182,
 'great': 183,
 'comedi': 184,
 'life': 185,
 'realli': 186,
 'come': 187,
 'fantasi': 188,
 'which': 189,
 'rather': 190,
 'tradit': 191,
 'dream': 192,
 'remain': 193,
 'solid': 194,
 'disappear': 195,
 'play': 196,
 'knowledg': 197,
 'particularli': 198,
 'concern': 199,
 'orton': 200,
 'halliwel': 201,
 'flat': 202,
 'mural': 203,
 'decor': 204,
 'everi': 205,
 'surfac': 206,
 'terribl': 207,
 'done': 208,
 'thought': 209,
 'way': 210,
 'spend': 211,
 'time': 212,
 'hot': 213,
 'summer': 214,
 'weekend': 215,
 'sit': 216,
 'air': 217,
 'condit': 218,
 'theater': 219,
 'lightheart': 220,
 'plot': 221,
 'simplist': 222,
 'dialogu': 223,
 'witti': 224,
 'charact': 225,
 'likabl': 226,
 'even': 227,
 'bread': 228,
 'suspect': 229,
 'serial': 230,
 'killer': 231,
 'disappoint': 232,
 'realiz': 233,
 'match': 234,
 'point': 235,
 '2': 236,
 'risk': 237,
 'addict': 238,
 'proof': 239,
 'woodi': 240,
 'allen': 241,
 'still': 242,
 'fulli': 243,
 'control': 244,
 'style': 245,
 'mani': 246,
 'us': 247,
 'grown': 248,
 'lovebr': 249,
 'thi': 250,
 'laugh': 251,
 'year': 252,
 'decad': 253,
 'impress': 254,
 'scarlet': 255,
 'johanson': 256,
 'manag': 257,
 'tone': 258,
 'sexi': 259,
 'imag': 260,
 'jump': 261,
 'averag': 262,
 'spirit': 263,
 'young': 264,
 'womanbr': 265,
 'crown': 266,
 'jewel': 267,
 'career': 268,
 'wittier': 269,
 'devil': 270,
 'wear': 271,
 'prada': 272,
 'interest': 273,
 'superman': 274,
 'friend': 275,
 'basic': 276,
 'there': 277,
 'famili': 278,
 'boy': 279,
 'jake': 280,
 'think': 281,
 'zombi': 282,
 'closet': 283,
 'parent': 284,
 'fight': 285,
 'timebr': 286,
 'movi': 287,
 'slower': 288,
 'soap': 289,
 'opera': 290,
 'suddenli': 291,
 'decid': 292,
 'rambo': 293,
 'zombiebr': 294,
 'ok': 295,
 'make': 296,
 'must': 297,
 'thriller': 298,
 'drama': 299,
 'watchabl': 300,
 'divorc': 301,
 'argu': 302,
 'like': 303,
 'real': 304,
 'total': 305,
 'ruin': 306,
 'expect': 307,
 'boogeyman': 308,
 'similar': 309,
 'instead': 310,
 'meaningless': 311,
 'spotsbr': 312,
 '3': 313,
 '10': 314,
 'descent': 315,
 'dialog': 316,
 'shot': 317,
 'ignor': 318,
 'them': 319,
 'petter': 320,
 'mattei': 321,
 'love': 322,
 'money': 323,
 'visual': 324,
 'stun': 325,
 'mr': 326,
 'offer': 327,
 'vivid': 328,
 'portrait': 329,
 'human': 330,
 'relat': 331,
 'seem': 332,
 'tell': 333,
 'power': 334,
 'success': 335,
 'peopl': 336,
 'differ': 337,
 'situat': 338,
 'encount': 339,
 'variat': 340,
 'arthur': 341,
 'schnitzler': 342,
 'theme': 343,
 'director': 344,
 'transfer': 345,
 'action': 346,
 'present': 347,
 'new': 348,
 'york': 349,
 'meet': 350,
 'connect': 351,
 'anoth': 352,
 'next': 353,
 'person': 354,
 'know': 355,
 'previou': 356,
 'contact': 357,
 'stylishli': 358,
 'sophist': 359,
 'luxuri': 360,
 'look': 361,
 'taken': 362,
 'live': 363,
 'world': 364,
 'habitatbr': 365,
 'soul': 366,
 'stage': 367,
 'loneli': 368,
 'inhabit': 369,
 'big': 370,
 'best': 371,
 'place': 372,
 'find': 373,
 'sincer': 374,
 'fulfil': 375,
 'discern': 376,
 'case': 377,
 'encounterbr': 378,
 'act': 379,
 'good': 380,
 'direct': 381,
 'steve': 382,
 'buscemi': 383,
 'rosario': 384,
 'dawson': 385,
 'carol': 386,
 'kane': 387,
 'imperioli': 388,
 'adrian': 389,
 'grenier': 390,
 'rest': 391,
 'talent': 392,
 'cast': 393,
 'alivebr': 394,
 'we': 395,
 'wish': 396,
 'luck': 397,
 'await': 398,
 'anxious': 399,
 'work': 400,
 'probabl': 401,
 'alltim': 402,
 'favorit': 403,
 'stori': 404,
 'selfless': 405,
 'sacrific': 406,
 'dedic': 407,
 'nobl': 408,
 'caus': 409,
 'preachi': 410,
 'bore': 411,
 'old': 412,
 'despit': 413,
 'seen': 414,
 '15': 415,
 'last': 416,
 '25': 417,
 'paul': 418,
 'luka': 419,
 'bring': 420,
 'tear': 421,
 'eye': 422,
 'bett': 423,
 'davi': 424,
 'sympathet': 425,
 'role': 426,
 'delight': 427,
 'kid': 428,
 'are': 429,
 'grandma': 430,
 'dressedup': 431,
 'midget': 432,
 'children': 433,
 'fun': 434,
 'mother': 435,
 'slow': 436,
 'awaken': 437,
 'what': 438,
 'roof': 439,
 'believ': 440,
 'startl': 441,
 'dozen': 442,
 'thumb': 443,
 'up': 444,
 'sure': 445,
 'resurrect': 446,
 'date': 447,
 'seahunt': 448,
 'seri': 449,
 'tech': 450,
 'today': 451,
 'back': 452,
 'excit': 453,
 'mei': 454,
 'grew': 455,
 'black': 456,
 'white': 457,
 'tv': 458,
 'gunsmok': 459,
 'hero': 460,
 'weekyou': 461,
 'vote': 462,
 'comeback': 463,
 'sea': 464,
 'huntw': 465,
 'need': 466,
 'chang': 467,
 'pace': 468,
 'water': 469,
 'adventureoh': 470,
 'thank': 471,
 'outlet': 472,
 'view': 473,
 'viewpoint': 474,
 'moviesso': 475,
 'ole': 476,
 'wanna': 477,
 'saywould': 478,
 'nice': 479,
 'read': 480,
 'plu': 481,
 'huntif': 482,
 'rhyme': 483,
 'line': 484,
 'let': 485,
 'submitor': 486,
 'leav': 487,
 'doubt': 488,
 'quitif': 489,
 'amaz': 490,
 'fresh': 491,
 'innov': 492,
 'idea': 493,
 '70': 494,
 '7': 495,
 '8': 496,
 'brilliant': 497,
 'drop': 498,
 'that': 499,
 '1990': 500,
 'funni': 501,
 'anymor': 502,
 'continu': 503,
 'declin': 504,
 'complet': 505,
 'wast': 506,
 'todaybr': 507,
 'disgrac': 508,
 'fallen': 509,
 'write': 510,
 'pain': 511,
 'bad': 512,
 'almost': 513,
 'mildli': 514,
 'entertain': 515,
 'respit': 516,
 'guesthost': 517,
 'hard': 518,
 'creator': 519,
 'handselect': 520,
 'origin': 521,
 'also': 522,
 'chose': 523,
 'band': 524,
 'hack': 525,
 'follow': 526,
 'recogn': 527,
 'brillianc': 528,
 'fit': 529,
 'replac': 530,
 'mediocr': 531,
 'felt': 532,
 'star': 533,
 'respect': 534,
 'made': 535,
 'huge': 536,
 'now': 537,
 'aw': 538,
 'cant': 539,
 'encourag': 540,
 'posit': 541,
 'comment': 542,
 'forward': 543,
 'mistak': 544,
 '950': 545,
 'worst': 546,
 'storylin': 547,
 'soundtrack': 548,
 'song': 549,
 'lame': 550,
 'countri': 551,
 'tune': 552,
 'less': 553,
 'four': 554,
 'cheap': 555,
 'rare': 556,
 'happi': 557,
 'end': 558,
 'credit': 559,
 'prevent': 560,
 '1score': 561,
 'harvey': 562,
 'keitel': 563,
 'least': 564,
 'bit': 565,
 'effort': 566,
 'obsess': 567,
 'onli': 568,
 'gut': 569,
 'wrench': 570,
 'laughter': 571,
 'hell': 572,
 'mom': 573,
 'itbr': 574,
 'camp': 575,
 'phil': 576,
 'alien': 577,
 'quirki': 578,
 'humour': 579,
 'base': 580,
 'odd': 581,
 'everyth': 582,
 'actual': 583,
 'punchlinesbr': 584,
 'at': 585,
 'progress': 586,
 'joke': 587,
 'anymorebr': 588,
 'low': 589,
 'budget': 590,
 'problem': 591,
 'itself': 592,
 'eventu': 593,
 'lost': 594,
 'interestbr': 595,
 'imagin': 596,
 'stoner': 597,
 'current': 598,
 'partakingbr': 599,
 'for': 600,
 'someth': 601,
 'better': 602,
 'tri': 603,
 'brother': 604,
 'planet': 605,
 '12': 606,
 'came': 607,
 'out': 608,
 'recal': 609,
 'scariest': 610,
 'bird': 611,
 'eat': 612,
 'men': 613,
 'dangl': 614,
 'helplessli': 615,
 'parachut': 616,
 'horror': 617,
 'horrorbr': 618,
 'as': 619,
 'cheesi': 620,
 'b': 621,
 'saturday': 622,
 'afternoon': 623,
 'tire': 624,
 'formula': 625,
 'monster': 626,
 'type': 627,
 'usual': 628,
 'includ': 629,
 'beauti': 630,
 'woman': 631,
 'might': 632,
 'daughter': 633,
 'professor': 634,
 'resolut': 635,
 'die': 636,
 'care': 637,
 'much': 638,
 'romant': 639,
 'angl': 640,
 'predict': 641,
 'unintent': 642,
 'humorbr': 643,
 'but': 644,
 'later': 645,
 'psycho': 646,
 'janet': 647,
 'leigh': 648,
 'bump': 649,
 'earli': 650,
 'sat': 651,
 'took': 652,
 'notic': 653,
 'sinc': 654,
 'screenwrit': 655,
 'scari': 656,
 'possibl': 657,
 'wellworn': 658,
 'rule': 659,
 'im': 660,
 'fan': 661,
 'boll': 662,
 'enjoy': 663,
 'postal': 664,
 'mayb': 665,
 'appar': 666,
 'bought': 667,
 'cri': 668,
 'long': 669,
 'ago': 670,
 'game': 671,
 'finsish': 672,
 'merc': 673,
 'infiltr': 674,
 'secret': 675,
 'research': 676,
 'lab': 677,
 'locat': 678,
 'tropic': 679,
 'island': 680,
 'warn': 681,
 'scheme': 682,
 'togeth': 683,
 'along': 684,
 'legion': 685,
 'schmuck': 686,
 'feel': 687,
 'loneley': 688,
 'invit': 689,
 'three': 690,
 'countrymen': 691,
 'with': 692,
 'player': 693,
 'name': 694,
 'til': 695,
 'schweiger': 696,
 'udo': 697,
 'kier': 698,
 'ralf': 699,
 'moellerbr': 700,
 'self': 701,
 'biz': 702,
 'tale': 703,
 'jack': 704,
 'carver': 705,
 'ye': 706,
 'german': 707,
 'hail': 708,
 'bratwurst': 709,
 'dude': 710,
 'howev': 711,
 'badass': 712,
 'complain': 713,
 'stay': 714,
 'true': 715,
 'whole': 716,
 'perspect': 717,
 'kick': 718,
 'a': 719,
 'beyond': 720,
 'dement': 721,
 'evil': 722,
 'mad': 723,
 'scientist': 724,
 'dr': 725,
 'krieger': 726,
 'geneticallymutatedsoldi': 727,
 'gm': 728,
 'topsecret': 729,
 'remind': 730,
 'spoiler': 731,
 'vancouv': 732,
 'reason': 733,
 'palm': 734,
 'tree': 735,
 'here': 736,
 'rich': 737,
 'lumberjackwood': 738,
 'gone': 739,
 'start': 740,
 'meheh': 741,
 'cannot': 742,
 'shenanigan': 743,
 'deliv': 744,
 'mean': 745,
 'suckbr': 746,
 'impli': 747,
 'area': 748,
 'boat': 749,
 'cromedalbino': 750,
 'squad': 751,
 'enter': 752,
 'reek': 753,
 'scheiss': 754,
 'poop': 755,
 'simpleton': 756,
 'take': 757,
 'wiff': 758,
 'ahead': 759,
 'btw': 760,
 'annoy': 761,
 'sidekick': 762,
 'shoot': 763,
 'minut': 764,
 'screen': 765,
 'shakespearebr': 766,
 'shakespear': 767,
 'lostbr': 768,
 'appreci': 769,
 'mass': 770,
 'goodbr': 771,
 'is': 772,
 'scottish': 773,
 'certain': 774,
 'rev': 775,
 'bowdler': 776,
 'henc': 777,
 'victorian': 778,
 'erabr': 779,
 'in': 780,
 'improv': 781,
 'perfectionbr': 782,
 'ten': 783,
 'text': 784,
 'and': 785,
 'english': 786,
 'composit': 787,
 'fort': 788,
 'keep': 789,
 'cut': 790,
 'fantast': 791,
 'famou': 792,
 'georg': 793,
 'clooney': 794,
 'roll': 795,
 'man': 796,
 'constant': 797,
 'sorrow': 798,
 'recommand': 799,
 'everybodi': 800,
 'greet': 801,
 'bart': 802,
 'kind': 803,
 'drawn': 804,
 'erot': 805,
 'amateurish': 806,
 'unbeliev': 807,
 'sort': 808,
 'school': 809,
 'project': 810,
 'rosanna': 811,
 'arquett': 812,
 'stock': 813,
 'bizarr': 814,
 'suppos': 815,
 'midwest': 816,
 'town': 817,
 'involv': 818,
 'lesson': 819,
 'learn': 820,
 'insight': 821,
 'stilt': 822,
 'quit': 823,
 'ridicul': 824,
 'lot': 825,
 'skin': 826,
 'intrigu': 827,
 'you': 828,
 'videotap': 829,
 'nonsensewhat': 830,
 'bisexu': 831,
 'relationship': 832,
 'nowher': 833,
 'heterosexu': 834,
 'absurd': 835,
 'danc': 836,
 'stereotyp': 837,
 'pass': 838,
 'million': 839,
 'mile': 840,
 'could': 841,
 'spent': 842,
 'starv': 843,
 'aid': 844,
 'africa': 845,
 'simpli': 846,
 'remad': 847,
 'fail': 848,
 'captur': 849,
 'flavor': 850,
 'terror': 851,
 '1963': 852,
 'titl': 853,
 'liam': 854,
 'neeson': 855,
 'excel': 856,
 'alway': 857,
 'hold': 858,
 'except': 859,
 'owen': 860,
 'wilson': 861,
 'luke': 862,
 'major': 863,
 'fault': 864,
 'version': 865,
 'stray': 866,
 'shirley': 867,
 'jackson': 868,
 'attempt': 869,
 'grandios': 870,
 'thrill': 871,
 'earlier': 872,
 'trade': 873,
 'snazzier': 874,
 'special': 875,
 'effect': 876,
 'friction': 877,
 'older': 878,
 'top': 879,
 'horribl': 880,
 'chanc': 881,
 'busi': 882,
 'run': 883,
 'sword': 884,
 'emot': 885,
 'attach': 886,
 'machin': 887,
 'want': 888,
 'destroy': 889,
 'blatantli': 890,
 'stolen': 891,
 'lotr': 892,
 'war': 893,
 'matrix': 894,
 'examplesbr': 895,
 'ghost': 896,
 'final': 897,
 'yoda': 898,
 'obe': 899,
 'vader': 900,
 'spider': 901,
 'begin': 902,
 'frodo': 903,
 'attack': 904,
 'return': 905,
 'king': 906,
 'elijah': 907,
 'wood': 908,
 'victim': 909,
 'waitit': 910,
 'hypnot': 911,
 'sting': 912,
 'wrap': 913,
 'upuh': 914,
 'hellobr': 915,
 'vs': 916,
 'matrixor': 917,
 'terminatorbr': 918,
 'exampl': 919,
 'someon': 920,
 'nazi': 921,
 'juvenil': 922,
 'rush': 923,
 'conclus': 924,
 'adult': 925,
 'either': 926,
 'just': 927,
 'save': 928,
 'rememb': 929,
 'filmit': 930,
 'cinema': 931,
 'dark': 932,
 'nervou': 933,
 '7475': 934,
 'dad': 935,
 'sister': 936,
 'newburi': 937,
 'berkshir': 938,
 'england': 939,
 'tiger': 940,
 'snow': 941,
 'appear': 942,
 'grizzli': 943,
 'adam': 944,
 'dan': 945,
 'haggeri': 946,
 'anyon': 947,
 'dvd': 948,
 'etc': 949,
 'pleas': 950,
 'knowth': 951,
 'club': 952,
 'shame': 953,
 'nearest': 954,
 '20': 955,
 'hear': 956,
 'other': 957,
 'stinker': 958,
 'nomin': 959,
 'golden': 960,
 'globe': 961,
 'femal': 962,
 'renaiss': 963,
 'painter': 964,
 'mangl': 965,
 'recognit': 966,
 'complaint': 967,
 'liberti': 968,
 'perfectli': 969,
 'fine': 970,
 'account': 971,
 'artist': 972,
 'dishwaterdul': 973,
 'script': 974,
 'enough': 975,
 'nake': 976,
 'factual': 977,
 'hurriedli': 978,
 'cap': 979,
 'summari': 980,
 'coupl': 981,
 'hour': 982,
 'favor': 983,
 'breviti': 984,
 'sequel': 985,
 'surpris': 986,
 'glut': 987,
 'cash': 988,
 'wrong': 989,
 'guy': 990,
 'concept': 991,
 'cliffhang': 992,
 'mountain': 993,
 'rescu': 994,
 'sli': 995,
 'stop': 996,
 'stallon': 997,
 'careerbr': 998,
 'nitpick': 999,
 ...}

In [192]:
len(vocab)

143272

In [193]:
df =data.copy()

In [194]:
result = {
    'positive':1,
    'negative':0
}

In [195]:
df.sentiment = df.sentiment.map(result)

In [196]:
df.head(5)

                                              review  sentiment
0  one review mention watch 1 oz episod hook righ...          1
1  wonder littl product br br the film techniqu u...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic there famili littl boy jake think there ...          0
4  petter mattei love time money visual stun film...          1

In [197]:
df.sentiment.values

array([1, 1, 1, ..., 0, 0, 0])

In [198]:
data = df.copy()

In [199]:
from nltk.tokenize import word_tokenize
df.review = df.review.apply(word_tokenize)

In [200]:
df.head(5)

                                              review  sentiment
0  [one, review, mention, watch, 1, oz, episod, h...          1
1  [wonder, littl, product, br, br, the, film, te...          1
2  [thought, wonder, way, spend, time, hot, summe...          1
3  [basic, there, famili, littl, boy, jake, think...          0
4  [petter, mattei, love, time, money, visual, st...          1

In [201]:
data = df.copy()

In [202]:
def vectorizzation(input):
  for i in range(len(input)):
      if input[i] in vocab.keys():
        input[i] = vocab[input[i]]
      else:
        input[i] = vocab['UNK']
  return input

In [203]:
df.review = df.review.apply(vectorizzation)

In [204]:
df.head(5)

                                              review  sentiment
0  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...          1
1  [144, 145, 146, 13, 13, 14, 147, 148, 149, 150...          1
2  [209, 144, 210, 211, 212, 213, 214, 215, 216, ...          1
3  [276, 277, 278, 145, 279, 280, 281, 277, 282, ...          0
4  [320, 321, 322, 212, 323, 324, 325, 147, 4, 32...          1

In [205]:
df.head(15)

                                               review  sentiment
0   [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...          1
1   [144, 145, 146, 13, 13, 14, 147, 148, 149, 150...          1
2   [209, 144, 210, 211, 212, 213, 214, 215, 216, ...          1
3   [276, 277, 278, 145, 279, 280, 281, 277, 282, ...          0
4   [320, 321, 322, 212, 323, 324, 325, 147, 4, 32...          1
5   [401, 402, 403, 287, 404, 405, 406, 407, 408, ...          1
6   [445, 85, 303, 170, 446, 447, 448, 449, 450, 4...          1
7   [27, 490, 491, 492, 493, 494, 15, 217, 15, 495...          0
8   [540, 541, 542, 147, 361, 543, 4, 147, 512, 54...          0
9   [303, 521, 569, 570, 571, 303, 287, 264, 412, ...          1
10  [576, 577, 1, 578, 147, 579, 580, 102, 581, 58...          0
11  [104, 287, 606, 607, 608, 609, 610, 20, 370, 6...          0
12  [660, 370, 661, 662, 400, 246, 429, 663, 287, ...          0
13  [393, 196, 766, 13, 767, 768, 13, 84, 769, 603...          0
14  [791, 287, 690, 55, 137, 792, 1, 159, 793, 794...          1